version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: products
    ports:
      - "5432:5432"
    networks:
      - backend

  nodejs:
    build:
      context: .
    depends_on:
      - postgres
    networks:
      - backend

networks:
  backend:
    driver: bridge
